version: "3"

services:
  database:
    image: postgres:latest
    volumes:
      - csdm_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: csdm
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "csdm"]

  backend:
    image: memateka:latest
    environment:
      SECRET_KEY: some-secret
      MAIL_SERVER: smtp.googlemail.com
      MAIL_PASSWORD: aneamkdcxjnuazpm
      MAIL_USERNAME: mrpostik
      MAIL_PORT: 587
      FLASK_DEBUG: 1
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: csdm
    ports:
      - 5000:5000
    depends_on:
      database:
        condition: service_healthy

volumes:
  csdm_db:
