"""4el

Revision ID: 92645b69edea
Revises: 
Create Date: 2022-06-06 15:41:26.714997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92645b69edea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True, comment='date of registation'),
    sa.Column('picture', sa.String(length=128), nullable=True, comment='link to avatar'),
    sa.Column('amount', sa.Integer(), nullable=True, comment='amount loaded mems'),
    sa.Column('uid', sa.String(length=128), nullable=False, comment='unique user id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(length=128), nullable=True, comment='unique id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=128), nullable=False, comment='Path mem image'),
    sa.Column('date', sa.DateTime(), nullable=True, comment='Date the meme was created'),
    sa.Column('description', sa.String(length=128), nullable=True, comment='Mem description'),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False, comment='Access level, 0 - private, 1 - public'),
    sa.Column('uid', sa.String(length=128), nullable=True, comment='unique id mem'),
    sa.Column('view', sa.Integer(), nullable=True, comment='Number of views'),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MemTag',
    sa.Column('mem_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mem_id'], ['mem.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    comment='Auxiliary table of meme and tag connection'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MemTag')
    op.drop_table('mem')
    op.drop_table('tag')
    op.drop_table('account')
    # ### end Alembic commands ###
